-- Migration 004: Create quotes table
CREATE TABLE IF NOT EXISTS `quotes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quote_number` VARCHAR(30) NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `status_id` INT UNSIGNED NOT NULL,
  `issue_date` DATE NOT NULL,
  `valid_until` DATE NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CLP',
  `tax_rate` DECIMAL(5,2) NOT NULL DEFAULT 19.00,
  `subtotal` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `discount_total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `tax_total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `total` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `notes` TEXT NULL,
  `terms` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_quotes_quote_number` (`quote_number`),
  KEY `idx_quotes_client_id` (`client_id`),
  KEY `idx_quotes_user_id` (`user_id`),
  KEY `idx_quotes_status_id` (`status_id`),
  KEY `idx_quotes_issue_date` (`issue_date`),
  KEY `idx_quotes_valid_until` (`valid_until`),
  CONSTRAINT `fk_quotes_client_id` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `fk_quotes_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `fk_quotes_status_id` FOREIGN KEY (`status_id`) REFERENCES `quote_statuses` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
